#!/bin/bash
#IPseen 0.01

if [ "$1" == "--mac" ]; then
    ip link show | awk '/ether/ {print $2}'
elif [ "$1" == "-private" ]; then
    ip addr show | awk '/inet (192\.168|10\.|172\.(1[6-9]|2[0-9]|3[01]))\./ {split($2, a, "/"); print a[1]}'
elif [ "$1" == "--public" ]; then
    dig +short myip.opendns.com @resolver1.opendns.com
elif [ "$1" == "--version" ]; then
    echo "IPseen 0.01"
    
elif [ "$1" == "--help" ]; then
    echo "IPseen		Show Private, Public and MAC Addresses"
    echo " "
    echo "IPseen --help 	Show this help command"
    echo "IPseen --version 	Show the current IPseen version"
    echo "IPseen --public	Show your Public IP Address"
    echo "IPseen --private	Show your Private IP Address"
    echo "IPseen --mac		Show your MAC Address"
else
    ip addr show
	echo Public IP Address: 
	dig +short myip.opendns.com @resolver1.opendns.com
fi
