#!/bin/bash
#IPseen 0.01

if [ "$1" == "--mac" ]; then
    ip link show | awk '/ether/ {print $2}'
elif [ "$1" == "--private" ]; then
    hostname -I
elif [ "$1" == "--public" ]; then
    dig +short myip.opendns.com @resolver1.opendns.com
elif [ "$1" == "--version" ]; then
    echo "IPseen 0.01"
    
elif [ "$1" == "--help" ]; then
    echo "IPseen		Show Private, Public and MAC Addresses"
    echo " "
    echo "IPseen --help 	Show this help command"
    echo "IPseen --version 	Show the current IPseen version"
    echo "IPseen --public	Show your Public IP Address"
    echo "IPseen --private	Show your Private IP Address"
    echo "IPseen --mac		Show your MAC Address"
else
	echo Private IP Address
    	hostname -I
	echo " "
	echo Public IP Address: 
	dig +short myip.opendns.com @resolver1.opendns.com
	echo " "
	echo Mac Address:
	ip link show | awk '/ether/ {print $2}'
fi
