#!/bin/bash
#IPseen 0.01

if [ "$1" == "--mac" ]; then
    ip link show | awk '/ether/ {print $2}'
elif [ "$1" == "--private" ]; then
    hostname -I
elif [ "$1" == "--public" ]; then
    curl https://ipinfo.io/ip
elif [ "$1" == "--version" ]; then
    echo "IPseen 0.01"
    
elif [ "$1" == "--help" ]; then
    echo "IPseen		Show Private, Public and MAC Addresses"
    echo " "
    echo "IPseen --help 	Show this help command"
    echo "IPseen --version 	Show the current IPseen version"
    echo "IPseen --public	Show your Public IP Address"
    echo "IPseen --private	Show your Private IP Address"
    echo "IPseen --mac		Show your MAC Address"
else
	echo -e "\033[1mPrivate IP Address:\033[0m"
    	hostname -I
	echo " "
	echo -e "\033[1mPublic IP Address:\033[0m"
	curl https://ipinfo.io/ip
	echo " "
	echo -e " "
	echo -e "\033[1mMAC Address:\033[0m"
	ip link show | awk '/ether/ {print $2}'
fi
